sudo: required
dist: trusty
language: node_js

node_js:
  - '4.4.2'

before_install:
  - sudo dpkg --add-architecture i386
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine1.8

  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono

  - 'cd PROTOTYPE/electron'

script:
  - 'npm install'
  - 'npm run build'

after_script:
  - 'cd PROTOTYPE/electron'
  - 'tar build-win32-x64 build-win32-x64.tar'

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: 
    - "./PROTOTYPE/electron/build-win32-x64.tar"
    - "PROTOTYPE/electron/build-win32-x64.tar"
    - "build-win32-x64.tar"
  skip_cleanup: true
  on:
    tags: true