dist: trusty
language: node_js

node_js:
  - '4.4.2'

before_install:
  - 'cd PROTOTYPE/electron'

script:
  - 'npm install'
  - 'npm run build'

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: "./PROTOTYPE/electron/build-win32-x64/LICENSE"
  skip_cleanup: true
  on:
    tags: true