sudo: required
dist: trusty
language: node_js

node_js:
  - '4.4.2'

before_install:
  - echo $TRAVIS_BUILD_DIR
  - pwd
  - sudo dpkg --add-architecture i386
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine1.8

  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono

  - 'cd PROTOTYPE/electron'

script:
  - 'npm install'
  - 'npm run build2'

after_script:
  - 'pwd'
  - 'ls'
  - 'zip -r build-win32-x64 build-win32-x64'

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file: 
    - "$TRAVIS_BUILD_DIR/PROTOTYPE/electron/build-win32-x64.zip"
    - "$TRAVIS_BUILD_DIR/PROTOTYPE/electron/dist/accessimap-lecteur-der-0.0.1-win.zip"
    - "$TRAVIS_BUILD_DIR/PROTOTYPE/electron/dist/accessimap-lecteur-der-0.0.1-x86_64.AppImage"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true